const db = require('quick.db')
const fetch = require('node-fetch')
const Discord = require('discord.js');

module.exports = {
    name: "gen",
    description: "Generate a key from the auth.gg panel",

    async run (client, message, args) {

    let days = parseInt(args[0])
    let amount = parseInt(args[1])
    let level = parseInt(args[2])
    let length = parseInt(args[3])
    let format = parseInt(args[4])

    let authkey = await db.get(`token_${message.guild.id}`)
    if(authkey === null) return message.channel.send(new Discord.MessageEmbed().setDescription(`The \`AuthKey\` **Has Not Been Set!**\n In Order To Use This Bot You Must Run The \`setauthkey\` Command First.`).setColor("RED").setTimestamp());

    if(!args[0]) return message.channel.send('Please Provide A Valid Amount Of Days');

    if(!args[1]) return message.channel.send('Please Provide A Valid Amount Of Keys');

    if(!args[2]) return message.channel.send('Please Provide A Valid Key Level');

    if(!args[3]) return message.channel.send('Please Provide A Valid Key Length');

    if(!args[4]) return message.channel.send('Please Provide A Valid Key Format');

    try {
    await fetch(`https://developers.auth.gg/LICENSES/?type=generate&days=${days}&amount=${amount}&level=${level}&length=${length}&format=${format}&authorization=${authkey}`)
    .then(res => res.json())
    .then(json => message.channel.send(new Discord.MessageEmbed().setTitle('Key Successfully Generated!').addField('Generated By:', message.author).addField('Key Generated:', `\`${json[0]}\``).setColor("GREEN").setTimestamp()));
    }catch(e) {
        message.channel.send(`ERROR: ${error}`)
    }
    }
}